/*
 * Generated by MTK Easy PinMux Tool Version 2.0.1 for 2533. Copyright MediaTek Inc. (C) 2015.
 * 2016-10-18 19:08:14:0829
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

const unsigned char BSP_GNSS_EINT = 1;
const unsigned char BSP_CTP_EINT = 10;
const unsigned char EXT_DSP_TRIGGER_EINT = 13;
const unsigned char HAL_ACCDET_EINT = 14;
const unsigned char HAL_MSDC_EINT = 0xff;
const unsigned char BSP_WIFI_EINT = 0xff;
const unsigned char MODEM_EXCEPTION_EINT = 0xff;
const unsigned char MODEM_WAKEUP_EINT = 0xff;
const unsigned char HAL_UART0_DTE_RI_EINT = 0xff;
const unsigned char HAL_UART0_DTE_DCD_EINT = 0xff;
const unsigned char HAL_UART0_DTE_DSR_EINT = 0xff;
const unsigned char HAL_UART1_DTE_RI_EINT = 0xff;
const unsigned char HAL_UART1_DTE_DCD_EINT = 0xff;
const unsigned char HAL_UART1_DTE_DSR_EINT = 0xff;
const unsigned char HAL_UART2_DTE_RI_EINT = 0xff;
const unsigned char HAL_UART2_DTE_DCD_EINT = 0xff;
const unsigned char HAL_UART2_DTE_DSR_EINT = 0xff;
const unsigned char HAL_UART3_TXD_PIN = 0xff;
const unsigned char HAL_UART3_RXD_PIN = 0xff;



