/*
 * Generated by MTK Easy PinMux Tool Version 2.1.0 for 7682. Copyright MediaTek Inc. (C) 2015.
 * 2017-05-16 11:29:26:0667
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

#ifndef  _EPT_EINT_DRV_H
#define  _EPT_EINT_DRV_H



#endif /* _EPT_EINT_DRV_H */
